create table ESTUDIANTE(
	ID number generated by default on null as identity,
	NOMBRE varchar2(255 byte) not null,
	APELLIDOS varchar2(255 byte) not null,
	DIRECCION varchar2(255 byte),
	CALIFICACION number not null,
constraint ESTUDIANTE_PK primary key 
	(
	ID
	)
);

create table PROFESOR (
	ID number generated by default on null as identity,
	NOMBRE varchar2(255 byte) not null,
	APELLIDOS varchar2(255 byte) not null,
	DIRECCION varchar2(255 byte),
	SALARIO number not null,
	TIENEPLAZA number (1,0) not null,
constraint PROFESOR primary key
	(
	ID
	)
);

create table CURSO(
	ID number generated by default on null as identity,
	NOMBRE varchar2(255 byte) not null,
	GRADO number (2,0) not null,
	IDPROFESOR number not null,
constraint CURSO_PK primary key
	(
	ID
	)
);

ALTER TABLE "CURSO" ADD CONSTRAINT "CURSOANTERIOR_FK"
    FOREIGN KEY ("CURSOANTERIOR") REFERENCES "CURSO"("ID");
ALTER TABLE "CURSO" ADD CONSTRAINT "CURSOSIGUIENTE_FK"
    FOREIGN KEY ("CURSOSIGUIENTE") REFERENCES "CURSO"("ID");
ALTER TABLE "CURSO" ADD CONSTRAINT "IDPROFESOR_FK"
    FOREIGN KEY ("IDPROFESOR") REFERENCES "PROFESOR"("ID");


COMMIT;

create table CURSOESTUDIANTE(
  ID number generated by default on null as identity,
	IDCURSO number not null,
	IDESTUDIANTE number not null,
	CALIFICACION number(3,0) not null,
constraint CURSOESTUDIANTE_PK primary key
	(
	ID
	)
);
ALTER TABLE "CURSOESTUDIANTE" ADD CONSTRAINT "IDCURSO_PK"
    FOREIGN KEY ("IDCURSO") REFERENCES "CURSO"("ID");
ALTER TABLE "CURSOESTUDIANTE" ADD CONSTRAINT "IDALUMNO_PK"
    FOREIGN KEY ("IDESTUDIANTE") REFERENCES "ESTUDIANTE"("ID");




INSERT INTO ESTUDIANTE (ID,NOMBRE,APELLIDOS,DIRECCION,CALIFICACION)
VALUES(1,'Adiel','Lara Ledesma','Los olivos 409', 95);


SELECT * FROM ESTUDIANTE

